"""initial migration

Revision ID: 16c1866d1d2c
Revises: 
Create Date: 2025-05-15 15:16:58.818693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c1866d1d2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cca3', sa.String(length=3), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('currency', sa.String(length=50), nullable=True),
    sa.Column('capital', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('subregion', sa.String(length=50), nullable=True),
    sa.Column('area', sa.BigInteger(), nullable=True),
    sa.Column('map_url', sa.String(length=255), nullable=True),
    sa.Column('population', sa.BigInteger(), nullable=True),
    sa.Column('flag_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country_neighbours',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('neighbour_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['neighbour_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('country_id', 'neighbour_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country_neighbours')
    op.drop_table('countries')
    # ### end Alembic commands ###
